CREATE TABLE schedule (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  matchNum VARCHAR(50) DEFAULT NULL,
  b1 INT DEFAULT NULL,
  b2 INT DEFAULT NULL,
  b3 INT DEFAULT NULL,
  r1 INT DEFAULT NULL,
  r2 INT DEFAULT NULL,
  r3 INT DEFAULT NULL,
  PRIMARY KEY (id)
);